name: CI

on:
  push:
    branches: [main, master]
  pull_request:

jobs:
  api-tests:
    name: API tests (pytest)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
        
      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install pytest requests

      - name: Run pytest
        env:
          API_BASE_URL: ${{ secrets.API_BASE_URL || 'https://dummyjson.com' }}
        run: pytest -m api -v --maxfail=1 --disable-warnings
      
  ui-tests:
    name: UI tests (Playwright)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Node deps
        run: |
          npm ci || npm install

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        env:
          UI_BASE_URL: ${{ secrets.UI_BASE_URL || 'https://www.demoblaze.com/' }}
        run: npx playwright test --reporter=html

      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report
          retention-days: 7
